import { describe, it, expect, vi } from 'vitest';
import { WAFDetector } from '../src/waf-detection';

describe('WAFDetector', () => {
	it('should return supported WAFs', () => {
		const wafs = WAFDetector.getSupportedWafs();
		expect(wafs).toContain('Cloudflare');
		expect(wafs).toContain('AWS WAF');
		expect(wafs).toContain('DDoS-Guard');
		expect(wafs).toContain('Qrator');
		expect(wafs).toContain('Wordfence');
		expect(wafs).toContain('Alibaba Cloud WAF');
		expect(wafs).toContain('StormWall');
		expect(wafs).toContain('Yandex Cloud WAF');
		expect(wafs).toContain('LiteSpeed');
		expect(wafs).toContain('PT Application Firewall');
		expect(wafs).toContain('Signal Sciences');
		expect(wafs).toContain('BunkerWeb');
		expect(wafs).toContain('OWASP Coraza');
		expect(wafs).not.toContain('Generic WAF'); // Generic should be filtered out
	});

	it('should detect Cloudflare WAF from headers', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'server') return 'cloudflare';
					if (name.toLowerCase() === 'cf-ray') return '123456789';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Cloudflare');
		expect(result.confidence).toBeGreaterThan(40);
		expect(result.evidence.length).toBeGreaterThan(0);
		expect(result.suggestedBypassTechniques.length).toBeGreaterThan(0);
	});

	it('should detect DDoS-Guard WAF from headers and cookies', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'server') return 'ddos-guard';
					if (name.toLowerCase() === 'set-cookie') return '__ddg1_=abc123; Path=/';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('DDoS-Guard');
		expect(result.confidence).toBeGreaterThan(40);
		expect(result.evidence.length).toBeGreaterThan(0);
		expect(result.suggestedBypassTechniques.length).toBeGreaterThan(0);
	});

	it('should detect Qrator WAF from headers and cookies', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'server') return 'qrator';
					if (name.toLowerCase() === 'set-cookie') return 'qrator_jsid=98765; Path=/';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Qrator');
		expect(result.confidence).toBeGreaterThan(40);
		expect(result.suggestedBypassTechniques.length).toBeGreaterThan(0);
	});

	it('should detect Wordfence WAF from headers, cookies, and body', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'x-wordfence-blocked') return '1';
					if (name.toLowerCase() === 'set-cookie') return 'wfwaf-authcookie=123';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse, 'Generated by Wordfence. Your access has been limited.');
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Wordfence');
		expect(result.confidence).toBeGreaterThan(40);
		expect(result.suggestedBypassTechniques).toContain('Alternative SQL comment syntax (/*#*/)');
	});

	it('should detect Alibaba Cloud WAF from headers and cookies', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'x-powered-by-aliwaf') return 'AliWAF';
					if (name.toLowerCase() === 'set-cookie') return 'ali_apache_track_id=12345';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Alibaba Cloud WAF');
		expect(result.suggestedBypassTechniques.length).toBeGreaterThan(0);
	});

	it('should detect StormWall from server and cookie headers', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'server') return 'stormwall';
					if (name.toLowerCase() === 'set-cookie') return 'strmwll=abc';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('StormWall');
	});

	it('should detect Yandex Cloud WAF from headers and cookies', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'x-yandex-waf') return 'active';
					if (name.toLowerCase() === 'set-cookie') return 'yandex_smartcaptcha=xyz';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Yandex Cloud WAF');
	});

	it('should detect LiteSpeed WAF from server header and body pattern', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => (name.toLowerCase() === 'server' ? 'LiteSpeed' : null),
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse, 'Access forbidden by rule');
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('LiteSpeed');
	});

	it('should detect PT Application Firewall from headers and cookies', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'x-ptaf') return '1';
					if (name.toLowerCase() === 'set-cookie') return 'ptaf_session=active';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('PT Application Firewall');
	});

	it('should detect BunkerWeb from server header and body patterns', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'server') return 'BunkerWeb';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse, 'This website is protected with BunkerWeb');
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('BunkerWeb');
	});

	it('should detect OWASP Coraza from headers and body pattern', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'x-coraza-waf') return '1';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse, 'blocked by OWASP Coraza');
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('OWASP Coraza');
	});

	it('should detect Imperva from new cookies and incident ID body', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => (name.toLowerCase() === 'set-cookie' ? 'nlbi_12345=abc; _incap_99=xyz' : null),
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse, 'Incident ID: 123456789-0');
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Imperva');
	});

	it('should detect F5 BIG-IP from TS cookie pattern', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => (name.toLowerCase() === 'set-cookie' ? 'TS01a2b3c4=12345; Path=/' : null),
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('F5 BIG-IP');
	});

	it('should detect Akamai from Bot Manager _abck cookie', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => (name.toLowerCase() === 'set-cookie' ? '_abck=token~0~1; Path=/' : null),
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Akamai');
	});

	it('should detect FortiWeb from FORTIWAFSID cookie', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => (name.toLowerCase() === 'set-cookie' ? 'FORTIWAFSID=1234567890; Path=/' : null),
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('FortiWeb');
	});

	it('should detect Citrix NetScaler from NSC_ cookie pattern', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => (name.toLowerCase() === 'set-cookie' ? 'NSC_ESNS=abcdef; Path=/' : null),
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Citrix NetScaler');
	});

	it('should detect AWS WAF from headers', async () => {
		const mockResponse = {
			status: 403,
			headers: {
				get: (name: string) => {
					if (name.toLowerCase() === 'x-amzn-requestid') return '123';
					return null;
				},
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('AWS WAF');
	});

	it('should return Unknown if no signatures match confidently', async () => {
		const mockResponse = {
			status: 200,
			headers: {
				get: () => null,
			},
		} as unknown as Response;

		const result = await WAFDetector.detectFromResponse(mockResponse);
		expect(result.detected).toBe(false);
		expect(result.wafType).toBe('Unknown');
	});

	it('should perform active detection using mock fetch', async () => {
		const mockFetch = vi.fn().mockResolvedValue({
			status: 403,
			headers: {
				get: (name: string) => (name.toLowerCase() === 'server' ? 'cloudflare' : null),
			},
			text: vi.fn().mockResolvedValue('cloudflare block page'),
		});

		const result = await WAFDetector.activeDetection('http://example.com/api', { fetch: mockFetch as any });

		expect(mockFetch).toHaveBeenCalled();
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Cloudflare');
	});

	it('should throw an error during active detection for invalid URLs', async () => {
		await expect(WAFDetector.activeDetection('http://127.0.0.1')).rejects.toThrow('Invalid URL or restricted IP');
	});

	it('should detect bypass opportunities using mock fetch', async () => {
		const mockFetch = vi.fn().mockImplementation((url, options) => {
			if (options.method === 'TRACE') {
				return Promise.resolve({ status: 200 }); // Not 405 -> httpMethodsBypass = true
			}
			if (options.headers && options.headers['X-Original-URL']) {
				return Promise.resolve({ status: 200 }); // headerBypass = true
			}
			if (url.includes('test=safe&test=malicious')) {
				return Promise.resolve({ status: 200 }); // parameterPollution = true
			}
			if (url.includes('%2527')) {
				return Promise.resolve({ status: 200 }); // encodingBypass = true
			}
			return Promise.resolve({ status: 403 });
		});

		const result = await WAFDetector.detectBypassOpportunities('http://example.com/api', { fetch: mockFetch as any });

		expect(result.httpMethodsBypass).toBe(true);
		expect(result.headerBypass).toBe(true);
		expect(result.encodingBypass).toBe(true);
		expect(result.parameterPollution).toBe(true);
	});
	
	it('should handle network errors in detectBypassOpportunities gracefully', async () => {
		const mockFetch = vi.fn().mockRejectedValue(new Error('Network connection timeout'));
		const result = await WAFDetector.detectBypassOpportunities('http://example.com/api', { fetch: mockFetch as any });
		expect(result.httpMethodsBypass).toBe(false);
		expect(result.headerBypass).toBe(false);
	});

	it('should detect WAF using activeDetection with captcha precedence and highest confidence', async () => {
		const mockFetch = vi.fn().mockImplementation((url) => {
			if (url.includes('test=')) {
				return Promise.resolve({
					status: 403,
					headers: {
						get: (name: string) => (name.toLowerCase() === 'server' ? 'cloudflare' : null),
					},
					text: () => Promise.resolve('cf-chl-bypass error'),
				});
			}
			return Promise.resolve({
				status: 200,
				headers: {
					get: () => null,
				},
				text: () => Promise.resolve('normal page'),
			});
		});

		const result = await WAFDetector.activeDetection('http://example.com/api', { fetch: mockFetch as any });
		expect(result.detected).toBe(true);
		expect(result.wafType).toBe('Cloudflare');
	});

	it('should return Unknown if activeDetection finds no WAF signatures', async () => {
		const mockFetch = vi.fn().mockResolvedValue({
			status: 200,
			headers: { get: () => null },
			text: () => Promise.resolve('ok clean page'),
		});

		const result = await WAFDetector.activeDetection('http://example.com/api', { fetch: mockFetch as any });
		expect(result.detected).toBe(false);
		expect(result.wafType).toBe('Unknown');
	});

	it('should throw an error during bypass detection for invalid URLs', async () => {
		await expect(WAFDetector.detectBypassOpportunities('http://169.254.169.254')).rejects.toThrow('Invalid URL or restricted IP');
	});

	describe('newly added vendor signatures', () => {
		// Build a Response whose header getter returns the provided map (case-insensitive).
		const mockResponse = (headers: Record<string, string>, status = 403): Response =>
			({
				status,
				headers: {
					get: (name: string) => headers[name.toLowerCase()] ?? null,
				},
			}) as unknown as Response;

		it('lists the new vendors as supported', () => {
			const wafs = WAFDetector.getSupportedWafs();
			for (const name of [
				'SafeDog', 'Jiasule', 'Yunjiasu', 'NSFOCUS', 'Comodo cWatch', 'Nemesida',
				'Tencent Cloud WAF', 'Anquanbao', 'Yunsuo',
			]) {
				expect(wafs).toContain(name);
			}
		});

		it('detects Tencent Cloud WAF from server header and body', async () => {
			const res = mockResponse({ server: 'tencent' });
			const result = await WAFDetector.detectFromResponse(res, 'Blocked by Tencent Cloud WAF: waf.tencent-cloud.com');
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Tencent Cloud WAF');
		});

		it('detects Anquanbao from its X-Powered-By header', async () => {
			const res = mockResponse({ 'x-powered-by-anquanbao': 'Miejd' });
			const result = await WAFDetector.detectFromResponse(res, 'aqb_cc/error page from Anquanbao');
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Anquanbao');
		});

		it('detects Yunsuo from its session cookie and body', async () => {
			const res = mockResponse({ 'set-cookie': 'yunsuo_session=abc; Path=/' });
			const result = await WAFDetector.detectFromResponse(res, 'blocked by _yunsuo_ protection');
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Yunsuo');
		});

		it('detects SafeDog from X-Powered-By header and cookie', async () => {
			const res = mockResponse({ 'x-powered-by': 'WAF/2.0', 'set-cookie': 'safedog-flow-item=abc; Path=/' });
			const result = await WAFDetector.detectFromResponse(res);
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('SafeDog');
			expect(result.suggestedBypassTechniques.length).toBeGreaterThan(0);
		});

		it('detects Jiasule from server header and cookie', async () => {
			const res = mockResponse({ server: 'jiasule-waf', 'set-cookie': '__jsluid=deadbeef; Path=/' });
			const result = await WAFDetector.detectFromResponse(res);
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Jiasule');
		});

		it('detects Yunjiasu from server header and 403 status', async () => {
			const res = mockResponse({ server: 'yunjiasu-nginx' });
			const result = await WAFDetector.detectFromResponse(res);
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Yunjiasu');
		});

		it('detects NSFOCUS from server header and body', async () => {
			const res = mockResponse({ server: 'NSFocus' });
			const result = await WAFDetector.detectFromResponse(res, 'Blocked by NSFOCUS WAF');
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('NSFOCUS');
		});

		it('detects Comodo cWatch from server header', async () => {
			const res = mockResponse({ server: 'Protected by COMODO WAF' });
			const result = await WAFDetector.detectFromResponse(res, 'Comodo WAF blocked this request');
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Comodo cWatch');
		});

		it('detects Nemesida from server header and body', async () => {
			const res = mockResponse({ server: 'nemesida' });
			const result = await WAFDetector.detectFromResponse(res, 'Nemesida WAF: Suspicious activity detected');
			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Nemesida');
		});
	});

	describe('Cloudflare /cdn-cgi/script_monitor/report probe', () => {
		const CDN_CGI_PATH = '/cdn-cgi/script_monitor/report';

		// Any non-probe request (the payload probes) resolves to a clean 200 so
		// only the /cdn-cgi probe can influence the outcome.
		const cleanResponse = () => ({
			status: 200,
			headers: { get: () => null },
			text: () => Promise.resolve('ok clean page'),
		});

		const probeResponder = (probe: { status: number; header?: (name: string) => string | null }) =>
			vi.fn().mockImplementation((url: string) => {
				if (url.includes(CDN_CGI_PATH)) {
					return Promise.resolve({
						status: probe.status,
						headers: { get: (name: string) => (probe.header ? probe.header(name.toLowerCase()) : null) },
						text: () => Promise.resolve('not found'),
					});
				}
				return Promise.resolve(cleanResponse());
			});

		it('detects Cloudflare when the probe path 404s with a server: cloudflare signature', async () => {
			const mockFetch = probeResponder({ status: 404, header: (n) => (n === 'server' ? 'cloudflare' : null) });

			const result = await WAFDetector.activeDetection('http://example.com/api', { fetch: mockFetch as any });

			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Cloudflare');
			expect(result.confidence).toBeGreaterThan(result.confidenceThreshold);
			expect(mockFetch).toHaveBeenCalledWith(
				'http://example.com/cdn-cgi/script_monitor/report',
				expect.objectContaining({ method: 'GET' }),
			);
			expect(result.evidence.some((e) => e.includes(CDN_CGI_PATH))).toBe(true);
		});

		it('detects Cloudflare when the probe path 404s with only a cf-ray header', async () => {
			const mockFetch = probeResponder({ status: 404, header: (n) => (n === 'cf-ray' ? '8ff0c0a1b2c3d4e5-FRA' : null) });

			const result = await WAFDetector.activeDetection('http://example.com/api', { fetch: mockFetch as any });

			expect(result.detected).toBe(true);
			expect(result.wafType).toBe('Cloudflare');
		});

		it('does not flag Cloudflare when the probe path 404s without any Cloudflare signature', async () => {
			const mockFetch = probeResponder({ status: 404, header: (n) => (n === 'server' ? 'nginx' : null) });

			const result = await WAFDetector.activeDetection('http://example.com/api', { fetch: mockFetch as any });

			expect(result.detected).toBe(false);
			expect(result.wafType).toBe('Unknown');
		});

		it('does not flag Cloudflare when the probe path returns 200 with a Cloudflare signature', async () => {
			const mockFetch = probeResponder({ status: 200, header: (n) => (n === 'server' ? 'cloudflare' : null) });

			const result = await WAFDetector.activeDetection('http://example.com/api', { fetch: mockFetch as any });

			expect(result.detected).toBe(false);
			expect(result.wafType).toBe('Unknown');
		});

		it('ignores the probe signature when running as a Cloudflare Worker (injected headers untrusted)', async () => {
			const mockFetch = probeResponder({ status: 404, header: (n) => (n === 'server' ? 'cloudflare' : null) });

			const result = await WAFDetector.activeDetection('http://example.com/api', { fetch: mockFetch as any, isWorker: true });

			expect(result.detected).toBe(false);
			expect(result.wafType).toBe('Unknown');
		});
	});
});
