export interface WAFSignature {
	name: string;
	headers: { [key: string]: string | RegExp };
	statusCodes?: number[];
	bodyPatterns?: RegExp[];
	cookiePatterns?: RegExp[];
	responseTime?: {
		min?: number;
		max?: number;
	};
}

export const WAF_SIGNATURES: WAFSignature[] = [
	// Cloudflare
	{
		name: 'Cloudflare',
		headers: {
			server: /cloudflare/i,
			'cf-ray': /^[a-f0-9]+-[A-Z]{3}$/,
			'cf-cache-status': /.*/,
			'cf-request-id': /.*/,
			'cf-mitigated': /.*/,
		},
		statusCodes: [403, 429],
		cookiePatterns: [/__cfduid/i, /cf_clearance/i, /__cf_bm/i, /__cf_chl/i],
		bodyPatterns: [
			/attention required! \| cloudflare/i,
			/ray id: [a-f0-9]+-[A-Z]{3}/i,
			/Cloudflare Ray ID:/i,
			/Please turn JavaScript on and reload the page\./i,
			/cdn-cgi\/challenge-platform/i,
			/cf_chl_opt/i,
			/cf_chl_tk/i,
			/<title>Just a moment...<\/title>/i,
			/Enable JavaScript and cookies to continue/i,
		],
	},

	// AWS WAF
	{
		name: 'AWS WAF',
		headers: {
			server: /awselb/i,
			'x-amzn-errortype': /waf/i,
			'x-amzn-waf-action': /.*/,
			'x-amzn-requestid': /.*/,
		},
		cookiePatterns: [/aws-waf-token/i],
		statusCodes: [403],
		bodyPatterns: [/AWS WAF/i, /403 ERROR.*The request could not be satisfied/i, /Request blocked\./i],
	},

	// BunkerWeb (Next-Gen WAF)
	{
		name: 'BunkerWeb',
		headers: {
			server: /bunkerweb/i,
			'x-bunkerweb': /.*/i,
			'x-bw-reason': /.*/i,
		},
		statusCodes: [403, 429, 503],
		cookiePatterns: [/^bw_/i, /bunkerweb/i],
		bodyPatterns: [
			/bunkerweb/i,
			/This website is protected with.*BunkerWeb/i,
			/Generating BunkerWeb config/i,
			/bunkerweb\.io/i,
		],
	},

	// OWASP Coraza (Next-Gen WAF)
	{
		name: 'OWASP Coraza',
		headers: {
			server: /coraza/i,
			'x-coraza': /.*/i,
			'x-coraza-waf': /.*/i,
		},
		statusCodes: [403],
		bodyPatterns: [
			/coraza/i,
			/OWASP Coraza/i,
			/corazawaf/i,
		],
	},

	// DDoS-Guard
	{
		name: 'DDoS-Guard',
		headers: {
			server: /ddos-guard/i,
		},
		cookiePatterns: [/__ddg1_/i, /__ddg2_/i, /__ddg5_/i, /__ddgid/i, /__ddgmark/i],
		statusCodes: [403, 429],
		bodyPatterns: [/ddos-guard/i, /ddg-captcha/i],
	},

	// Qrator Labs
	{
		name: 'Qrator',
		headers: {
			server: /qrator/i,
			'x-qrator-trace-id': /.*/,
		},
		cookiePatterns: [/qrator_jsid/i, /qrator_jsr/i, /qrator_msid/i, /qrator_ssid/i],
		statusCodes: [403, 429],
		bodyPatterns: [/qrator\.net/i, /QRATOR/i, /Access Denied - Qrator/i],
	},

	// Wordfence (WordPress WAF)
	{
		name: 'Wordfence',
		headers: {
			'x-wordfence-blocked': /.*/,
			'x-wordfence-action': /.*/,
		},
		cookiePatterns: [/wfwaf-authcookie/i, /wfvt_/i],
		statusCodes: [403, 503],
		bodyPatterns: [
			/Generated by Wordfence/i,
			/Your access to this site has been limited at this time/i,
			/Wordfence Web Application Firewall/i,
			/Block Reason: .*Wordfence/i,
		],
	},

	// Alibaba Cloud WAF (AliYunDun)
	{
		name: 'Alibaba Cloud WAF',
		headers: {
			'x-powered-by-aliwaf': /.*/,
			'x-ali-cluster': /.*/,
		},
		cookiePatterns: [/ali_apache_track_id/i, /aliwaf/i, /alw_/i],
		statusCodes: [403, 405],
		bodyPatterns: [/errors\.aliyun\.com/i, /AliYunDun/i, /Alibaba Cloud Security/i],
	},

	// StormWall
	{
		name: 'StormWall',
		headers: {
			server: /stormwall/i,
			'x-stormwall-id': /.*/,
		},
		cookiePatterns: [/strmwll/i, /_sw_/i],
		statusCodes: [403, 429],
		bodyPatterns: [/stormwall\.pro/i, /StormWall WAF/i, /Protected by StormWall/i],
	},

	// Yandex Cloud WAF & SmartCaptcha
	{
		name: 'Yandex Cloud WAF',
		headers: {
			'x-yandex-waf': /.*/,
		},
		cookiePatterns: [/yandex_smartcaptcha/i, /ysp_/i],
		statusCodes: [403, 429],
		bodyPatterns: [/smartcaptcha\.yandexcloud\.net/i, /Yandex SmartCaptcha/i],
	},

	// LiteSpeed Web Server WAF
	{
		name: 'LiteSpeed',
		headers: {
			server: /LiteSpeed/i,
			'x-litespeed-cache': /.*/,
		},
		statusCodes: [403],
		bodyPatterns: [/Proudly powered by LiteSpeed/i, /Access forbidden by rule/i],
	},

	// Positive Technologies (PT AF)
	{
		name: 'PT Application Firewall',
		headers: {
			'x-ptaf': /.*/,
			'x-pt-af': /.*/,
		},
		cookiePatterns: [/ptaf_session/i, /PTAF/i],
		statusCodes: [403],
		bodyPatterns: [/PT Application Firewall/i],
	},

	// Imperva/Incapsula
	{
		name: 'Imperva',
		headers: {
			'x-iinfo': /.*/,
			'x-cdn': /Incapsula/i,
		},
		statusCodes: [403],
		cookiePatterns: [/incap_ses_/i, /visid_incap_/i, /nlbi_/i, /_incap_/i],
		bodyPatterns: [
			/request unsuccessful\. incapsula incident id/i,
			/Incident ID: [0-9-]+/i,
			/Powered By Incapsula/i,
			/errors\.imperva\.com/i,
		],
	},

	// F5 BIG-IP
	{
		name: 'F5 BIG-IP',
		headers: {
			server: /BIG-IP/i,
			'x-wa-info': /.*/,
			'f5-trace-id': /.*/,
		},
		cookiePatterns: [/TS[0-9a-f]{8}/i, /BIGipServer/i, /f5_cspm/i],
		statusCodes: [403],
		bodyPatterns: [/the requested url was rejected/i, /please consult with your administrator/i, /your support id is/i],
	},

	// ModSecurity
	{
		name: 'ModSecurity',
		headers: {
			server: /mod_security/i,
			'x-mod-security': /.*/,
		},
		statusCodes: [403, 406],
		bodyPatterns: [/Mod_Security/i, /mod_security/i, /request blocked by security policy/i, /OWASP.*CRS/i],
	},

	// Akamai
	{
		name: 'Akamai',
		headers: {
			server: /AkamaiGHost/i,
			'akamai-origin-hop': /.*/,
			'x-akamai-transformed': /.*/,
			'x-akamai-request-id': /.*/,
			'x-akamai-session-info': /.*/,
		},
		cookiePatterns: [/ak_bmsc/i, /bm_sz/i, /bm_sv/i, /_abck/i],
		statusCodes: [403],
		bodyPatterns: [/reference #[0-9a-f.]+/i, /You don't have permission to access .* on this server/i],
	},

	// Barracuda
	{
		name: 'Barracuda',
		headers: {
			server: /Barracuda/i,
			'x-barracuda-url': /.*/,
		},
		cookiePatterns: [/barra_counter_session/i, /BNI_/i, /BNI__B_USER_LOOKUP/i],
		statusCodes: [403],
		bodyPatterns: [/barracuda/i],
	},

	// Sucuri
	{
		name: 'Sucuri',
		headers: {
			server: /Sucuri/i,
			'x-sucuri-id': /.*/,
			'x-sucuri-cache': /.*/,
		},
		statusCodes: [403],
		bodyPatterns: [/sucuri website firewall - access denied/i, /questions\? contact us at cloudproxy@sucuri\.net/i],
	},

	// Fastly
	{
		name: 'Fastly',
		headers: {
			via: /fastly/i,
			'x-served-by': /cache-.*-fastly/i,
			'x-cache': /(HIT|MISS).*fastly/i,
		},
		statusCodes: [403],
	},

	// KeyCDN
	{
		name: 'KeyCDN',
		headers: {
			server: /keycdn-engine/i,
			'x-edge-location': /.*/,
		},
		statusCodes: [403],
	},

	// StackPath (MaxCDN)
	{
		name: 'StackPath',
		headers: {
			server: /NetDNA-cache|stackpath/i,
			'x-hw': /.*/,
		},
		statusCodes: [403],
	},

	// DenyAll
	{
		name: 'DenyAll',
		headers: {
			server: /denyall/i,
		},
		statusCodes: [403],
		bodyPatterns: [/denyall/i],
	},

	// Fortinet FortiWeb
	{
		name: 'FortiWeb',
		headers: {
			server: /Fortigate|FortiWeb/i,
			'x-powered-by': /FortiWeb/i,
		},
		cookiePatterns: [/FORTIWAFSID=/i],
		statusCodes: [403],
		bodyPatterns: [/web filter violation/i, /fortigate/i, /fortiweb/i],
	},

	// Wallarm
	{
		name: 'Wallarm',
		headers: {
			server: /nginx-wallarm/i,
			'x-wallarm-instance': /.*/,
			'x-wallarm-inline': /.*/,
			'x-wallarm-request-id': /.*/,
		},
		statusCodes: [403, 500],
	},

	// Radware AppWall
	{
		name: 'Radware',
		headers: {
			server: /Radware|AppWall/i,
			'x-origin-requestid': /.*/,
			'x-sl-compflag': /.*/,
		},
		cookiePatterns: [/rdwr_session/i],
		statusCodes: [403],
	},

	// Azure Front Door
	{
		name: 'Azure Front Door',
		headers: {
			'x-azure-ref': /.*/,
			server: /Microsoft-HTTPAPI\/2\.0/i,
		},
		statusCodes: [403],
		bodyPatterns: [/Our services aren't available right now/i, /Microsoft-Azure-Application-Gateway/i],
	},

	// Google Cloud Armor
	{
		name: 'Google Cloud Armor',
		headers: {
			server: /^GSE$/i,
		},
		statusCodes: [403, 404],
		bodyPatterns: [/Request blocked by Cloud Armor/i, /Access Denied.*Cloud Armor/i],
	},

	// Citrix NetScaler
	{
		name: 'Citrix NetScaler',
		headers: {
			server: /NetScaler/i,
			'vi-id': /.*/,
		},
		cookiePatterns: [/ns_af=/i, /citrix_ns_id/i, /NSC_/i],
		statusCodes: [403],
		bodyPatterns: [/The requested URL was rejected\. Please consult with your administrator/i, /NS-CACHE/i],
	},

	// Varnish (often used with WAF modules)
	{
		name: 'Varnish',
		headers: {
			server: /varnish/i,
			'x-varnish': /.*/,
			via: /varnish/i,
		},
		statusCodes: [403],
	},

	// Palo Alto Networks
	{
		name: 'Palo Alto Networks',
		headers: {
			'x-phx': /.*/,
		},
		statusCodes: [403],
		bodyPatterns: [/Virus\/Spyware Download Blocked/i, /Palo Alto Next Generation Security Platform/i],
	},

	// Sophos WAF
	{
		name: 'Sophos WAF',
		headers: {
			'x-sophos-waf-id': /.*/,
		},
		cookiePatterns: [/sophos_waf_id/i],
		statusCodes: [403],
		bodyPatterns: [/Powered by UTM Web Protection/i, /Sophos Firewall/i],
	},

	// --- New Signatures Added ---
	
	// Signal Sciences (Fastly Next-Gen WAF)
	{
		name: 'Signal Sciences',
		headers: {
			'x-sigsci-request-id': /.*/,
			'x-sigsci-tags': /.*/,
		},
		statusCodes: [406],
	},

	// NGINX App Protect / NAXSI
	{
		name: 'NGINX App Protect',
		headers: {
			'x-naxsi-sig': /.*/,
		},
		statusCodes: [403],
		bodyPatterns: [/The request was rejected/i, /NAXSI/i, /nginx app protect/i],
	},

	// HAProxy Enterprise WAF
	{
		name: 'HAProxy',
		headers: {},
		statusCodes: [403],
		bodyPatterns: [/HAProxy/i, /Protected by HAProxy/i],
	},

	// IBM DataPower
	{
		name: 'IBM DataPower',
		headers: {
			'x-backside-transport': /.*/,
			'x-dp-watson-tran-id': /.*/,
		},
		statusCodes: [403],
		bodyPatterns: [/DataPower/i, /Transaction Error/i],
	},

	// Reblaze
	{
		name: 'Reblaze',
		headers: {
			server: /Reblaze Secure Web Gateway/i,
		},
		cookiePatterns: [/rbzid=/i],
		statusCodes: [403],
		bodyPatterns: [/Reblaze/i, /Access denied by Reblaze/i],
	},

	// DotDefender
	{
		name: 'DotDefender',
		headers: {
			'x-dotdefender-denied': /.*/,
		},
		statusCodes: [403],
		bodyPatterns: [/dotDefender Blocked Your Request/i],
	},

	// SafeDog (Website Security Dog / 安全狗)
	{
		name: 'SafeDog',
		headers: {
			'x-powered-by': /WAF\/2\.0/i,
			server: /safedog/i,
		},
		cookiePatterns: [/safedog-flow-item/i],
		statusCodes: [403, 404, 406, 502],
		bodyPatterns: [/safedog/i, /404\.safedog\.cn/i, /404\.safedog\.com\.cn/i],
	},

	// Jiasule (SCloud / 加速乐)
	{
		name: 'Jiasule',
		headers: {
			server: /jiasule-waf/i,
		},
		cookiePatterns: [/__jsluid/i, /__jsl_clearance/i, /jsl_tracking/i],
		statusCodes: [403],
		bodyPatterns: [/notice-jiasule/i, /www\.jiasule\.com/i, /static\.jiasule\.com/i],
	},

	// Yunjiasu (Baidu Cloud WAF)
	{
		name: 'Yunjiasu',
		headers: {
			server: /yunjiasu(-nginx)?/i,
		},
		statusCodes: [403],
		bodyPatterns: [/yunjiasu/i],
	},

	// NSFOCUS Web Application Firewall
	{
		name: 'NSFOCUS',
		headers: {
			server: /NSFocus/i,
		},
		statusCodes: [403],
		bodyPatterns: [/NSFOCUS/i, /nsfocus\.com/i],
	},

	// Comodo cWatch WAF
	{
		name: 'Comodo cWatch',
		headers: {
			server: /Protected by COMODO WAF/i,
		},
		statusCodes: [403],
		bodyPatterns: [/Comodo WAF/i, /cwatch/i, /Protected by COMODO WAF/i],
	},

	// Nemesida WAF
	{
		name: 'Nemesida',
		headers: {
			server: /nemesida/i,
		},
		statusCodes: [403, 222],
		bodyPatterns: [/Nemesida WAF/i, /nemesida-security\.com/i, /Suspicious activity detected\. Access to the site is blocked/i],
	},

	// Tencent Cloud WAF (T-Sec)
	{
		name: 'Tencent Cloud WAF',
		headers: {
			server: /tencent/i,
		},
		statusCodes: [403],
		bodyPatterns: [/waf\.tencent-cloud\.com/i, /tencent cloud waf/i, /Blocked by Tencent Cloud/i],
	},

	// Anquanbao (安全宝)
	{
		name: 'Anquanbao',
		headers: {
			'x-powered-by-anquanbao': /.*/i,
		},
		statusCodes: [403, 405],
		bodyPatterns: [/Anquanbao/i, /aqb_cc\/error/i, /aqb\.html/i],
	},

	// Yunsuo (云锁)
	{
		name: 'Yunsuo',
		headers: {},
		cookiePatterns: [/yunsuo_session/i],
		statusCodes: [403],
		bodyPatterns: [/_yunsuo_/i, /yunsuo\.com\.cn/i, /security_verify_/i],
	},

	// Generic detection patterns — require WAF-specific phrases,
	// not just common HTTP words like "forbidden"
	{
		name: 'Generic WAF',
		headers: {},
		statusCodes: [403, 406, 429],
		bodyPatterns: [
			/request.*(blocked|rejected|filtered).*by/i,
			/web.*(firewall|application firewall|waf)/i,
			/malicious.*request|suspicious.*activity|attack.*detected/i,
		],
	},
];
